events {
    worker_connections 1024;
}

http {
    # CRITICALLY IMPORTANT: Connecting data types so that the browser understands CSS/JS/HTML
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Logging and optimization settings (optional, for stability)
    sendfile        on;
    keepalive_timeout  65;

    limit_req_zone $binary_remote_addr zone=separate_limit:10m rate=6r/m;

    # The main HTTPS server
    server {
        listen 80;
        client_max_body_size 50M;

        location /api/separate {
            limit_req zone=separate_limit burst=2 nodelay;
            proxy_pass http://api:8000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location / {
            proxy_pass http://api:8000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
