{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info{}, app_name)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requests by endpoint",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(handler)(\r\n    rate(http_requests_total{handler!=\"/metrics\"}[5m])\r\n)"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(http_request_duration_highr_seconds_bucket[5m])))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Error rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\"}[5m])) or vector(0))/sum(rate(http_requests_total[5m]))*100",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "The speed of posting messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[5m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "RAM FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "CPU FastAPI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 12 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(fastapi_requests_duration_seconds_bucket{app_name=\"$app_name\", path!=\"/metrics\"}[1m])) by(path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=~\"app-.*\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | type != \"\" |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "{compose_service=~\"app-.*\"} | pattern `<date> <time> <type> <logger> <code> [<_>=<trace_id> <_>=<span_id> <_>=<service_name>] - <msg>` | line_format \"{{.compose_service}}\\t{{.type}}\\t trace_id={{.trace_id}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}