"""add browser sessions

Revision ID: 1003d1fac3a0
Revises: 31f16d62fc36
Create Date: 2026-06-19 18:10:30.182622

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1003d1fac3a0'
down_revision: Union[str, Sequence[str], None] = '31f16d62fc36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_expires_at'), 'browser_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_browser_sessions_token'), 'browser_sessions', ['token'], unique=True)
    op.add_column('jobs', sa.Column('session_id', sa.Uuid(), nullable=True))
    # First, we create a "stub" in the session table so that the Foreign Key does not swear
    op.execute("""
        INSERT INTO browser_sessions (id, token, created_at, last_seen_at, expires_at) 
        VALUES ('00000000-0000-0000-0000-000000000000', 'migration_dummy_token', NOW(), NOW(), NOW() + INTERVAL '1 day')
        ON CONFLICT DO NOTHING
    """)
    # It's safe to update old jobs now
    op.execute("UPDATE jobs SET session_id = '00000000-0000-0000-0000-000000000000' WHERE session_id IS NULL")
    # Enabling NOT NULL and Foreign Key
    op.alter_column('jobs', 'session_id', nullable=False)
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    op.create_foreign_key(
        "fk_jobs_session_id_browser_sessions",
        "jobs", "browser_sessions", ["session_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_jobs_session_id_browser_sessions", "jobs", type_="foreignkey")
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_column('jobs', 'session_id')
    op.drop_index(op.f('ix_browser_sessions_token'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_expires_at'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    # ### end Alembic commands ###
